- name: Sentry Release
  # You may pin to the exact commit or the version.
  # uses: getsentry/action-release@526942b68292201ac6bbb99b9a0747d4abee354c
  uses: getsentry/action-release@v3.2.0
  with:
    # Set the environment for this release. E.g. "production" or "staging".
Omit to skip adding deploy to release.
    environment: # optional
    # Space-separated list of paths to JavaScript source maps.
Omit to skip uploading sourcemaps.
    sourcemaps: # optional
    # Injects Debug IDs into source files and source maps to ensure proper
un-minifcation of your stacktraces.
Does nothing if "sourcemaps" was not set.
    inject: # optional, default is true
    # Unique identifier for the distribution, used to further segment your
release.
Usually your build number.
    dist: # optional
    # When false, omit marking the release as finalized and released.
    finalize: # optional, default is true
    # When the flag is set and the previous release commit was not found in
the repository, will create a release with the default commits count
instead of failing the command.
    ignore_missing: # optional
    # When the flag is set, command will not fail and just exit silently if no
new commits for a given release have been found.
    ignore_empty: # optional
    # Unix timestamp of the release start date. Omit for current time.
    started_at: # optional
    # Identifier that uniquely identifies the release.
Should match the "release" property in your Sentry SDK init call if one
was set.
Omit to auto-generate one.
    version: # optional
    # Identifier that uniquely identifies the release.
Should match the "release" property in your Sentry SDK init call if one
was set.
Omit to auto-generate one.
    release: # optional
    # Value prepended to auto-generated version.
    version_prefix: # optional
    # Value prepended to auto-generated release version.
    release_prefix: # optional
    # Specify whether to set commits for the release.
One of: "auto", "skip"
    set_commits: # optional
    # Space-separated list of projects.
Defaults to the env variable "SENTRY_PROJECT" if not provided.
    projects: # optional
    # Adds a prefix to source map urls after stripping them.
    url_prefix: # optional
    # Will remove a common prefix from uploaded filenames. Useful for removing
a path that is build-machine-specific.
Note: Will not remove common prefixes across two or more directories
provided to "sourcemap". E.g. Setting
"sourcemap": "./dist/js ./dist/asset/js" will strip "./dist" for the first
directory and "./dist/assets/js" for the
    strip_common_prefix: # optional
    # Directory to collect sentry release information from.
Useful when collecting information from a non-standard checkout directory.
    working_directory: # optional
    # The action sends telemetry data and crash reports to Sentry. This helps
us improve the action.
You can turn this off by setting this flag.
    disable_telemetry: # optional
    # The action needs access to the repo it runs in. For that we need to
configure git to mark the repo directory a safe directory.
You can turn this off by setting this flag.
    disable_safe_directory: # optional
          
